### PR TITLE
more bitcoin 0.12 migration

### PR DESCRIPTION
**Pull request by GregoryBetz**

### CODE REVIEW

**Comment by CryptoDJ** [comment]
It looks like there will be two Qt project files.  empinel renamed the last one (darksilk-qt.pro --> darksilk.pro) and this pull adds darksilk-qt.pro back so I think we will have two.

**Comment by empinel** [comment]
I will need UniValue for my next series of commits (darksilk-tx)

**Comment by empinel** [comment]
https://github.com/empinel/DarkSilk-Release-Candidate/commit/5ac5403bcfe0042f764c57af94a0b1cd329fff38

**Comment by GregoryBetz** [comment]
i will just revert it back to darksilk.pro then

**Pull request closed without merging**
