### PR TITLE
ChainParamsBase: new file additions

### PR DESCRIPTION
**Pull request by GregoryBetz**
#### What's this pull request do?
Adds chainparamsbase.h/cpp, which is required for darksilk-cli.cpp as well as other upgrades.
#### Did you test this pull request?
Does not require testing yet.
#### Any background context you want to provide?
This is just a simple first step towards more integration with bitcoin 0.12.99, and in particular, upgrading RPC functions from using json_spirit to UniValue.
#### Questions:
- Does the readme or documentaion need an update? No.
- Does this add new C++ dependencies which need to be added? No.
- Does this change the chain or fork the network? No.

### CODE REVIEW

**Comment by SCDeveloper** [comment]
You will need to build test as I am sure you will need to fix includes.

**Comment by empinel** [comment]
I already introduced darksilk-cli

**Comment by GregoryBetz** [comment]
There is still more to do. Once I have completed chainparamsbase (which is required for a fully functional darksilk-cli btw), and darksilk-cli, prevector, etc. Then we can switch json_spirit to Univalue. It will ultimately speed up the wallet and use less memory. So, keep working on it and I will too!

**Comment by empinel** [comment]
Are you seriously using emoji? Can you please do a thing - I have shifted some variables to ChainParams (available in my repo), can you please integrate that into your repo as well? As I had to edit a lot of files and it's a clash nightmare

**Comment by empinel** [comment]
Otherwise, I am working on my exams and libevent for RPC

**Comment by GregoryBetz** [comment]
I changed some functions in chainparams too. I have the daemon compiled successfully. I need to edit some qt files yet, to enable a succesful build of the Core wallet.

**Pull request closed without merging**
