### PR TITLE
Addition of CScheduler, Miscellaneous Fixes, Addition of a CLI Server and others....

### PR DESCRIPTION
**Pull request by empinel**
#### What's this pull request do?

Add the CScheduler Class, Add a REST API, a stub CLI Server (stub because of absence of makefile for CLI), addition of our own reverse lock (for CScheduler) and the addition of a Tor Server for Networking, it also has miscellanious bugfixes

#### Where should the reviewer start?

Wherever he wants to

#### Did you test this pull request?

Mostly

#### Any background context you want to provide?

The addition of the event library will be required and snappy is still debatable

#### Screenshots (if appropriate)

N/A, No Qt Fixes

#### Questions:
- Does the readme or documentaion need an update?

Yes, the addition of LibEvent will be required

- Does this add new C++ dependencies which need to be added?

Affirmative, libevent

- Does this change the chain or fork the network?

No

NOTE: The pull request will have to be enacted as a non-nano pull request as all the commits were dirty and then there were a tiny series of commits that fix them and clean them

### CODE REVIEW

**Comment by empinel** [comment]
Changes to the comment to be elaborate have been done, Amir - I can't make them micro as the initial commits are dirty and separating the commits that fixes the dirtiness from the commits that are dirty is an unnecessary mess - proper measures will be taken in the future

**Comment by SCDeveloper** [comment]
This commit looks good. You have created a pow.cpp/h but it also contains pos functions, so, maybe a file namechange is best.

**Comment by GregoryBetz** [comment]
It builds but then gives an error when you try and run the qt-wallet.
"EXCEPTION: St13runtime_error
tinyformat: Not enough conversion specifiers in format string"

**Comment by CryptoDJ** [comment]
[src/i2psam.cpp](https://github.com/SCDeveloper/DarkSilk-Release-Candidate/pull/180/files#diff-a64408f06db06271308b70195e671253R149) this line should be changed 
from:
`LogPrintf("[I2P] Send: ", msg);`

to this:

`LogPrintf("[I2P] Send: %s", msg);`

without the `%s` it will cause a segfault because it doesn't know where to insert the msg variable.  I see the same mistake several times in src/i2psam.cpp when using  LogPrintf.

**Comment by GregoryBetz** [comment]
That fixed the segfault error, thanks. However, torcontrol does not shutdown with the rest of the wallet. It keeps trying to connect on an endless loop. So, I'm now looking at where to place a shutdown function.

**Comment by GregoryBetz** [comment]
I found the fix for the looping tor connector here: https://github.com/bitcoin/bitcoin/pull/7637/commits/e2195037116f47b11b66452351dba4fe606423a2

According to the debug.log, every component is shutting down properly, but the .lock is never released. Any ideas?

**Comment by empinel** [comment]
gdb could be of help

**Comment by empinel** [comment]
@SCDeveloper As per BTC Standards, we need to name to pow.cpp, but if deemed necessary (by you) then i will rename it to proofs.cpp

**Comment by SCDeveloper** [comment]
We are not Bitcoin, we are better. Rename to proofs.cpp ;)

**Comment by CryptoDJ** [comment]
Why are you adding to an already overloaded pull request?  Please remove your last pull and submit it as a snip and different pull request.

**Comment by empinel** [comment]
Okay Amir, I will put the taxes to another branch

**Comment by empinel** [comment]
This is too stagnant, I am closing this

**Pull request closed without merging**
