### PR TITLE
[Library][Passphrase] Switch the password generation algorithm to ctAES

### PR DESCRIPTION
**Pull request by empinel**
#### What is the purpose of this pull request (PR)?

Switching the password generation algorithm to ctAES

#### Any background context to help the reviewer?

No

#### Was this PR tested and how (if not, why)?

Yes

#### Does this PR resolve an open issue (reference issue #)?
1. Fixes issue #

#### More Questions:
- Does the knowledge base need an update? No
- Does this PR add or change dependencies? No
- Does this change the chain or fork the network? No

### CODE REVIEW

**Comment by SCDeveloper** [comment]
Was thinking of using Argon2d for the password. Thoughts?

**Comment by empinel** [comment]
Well, this adheres to BitCoin's standards and we will get increased and improved support rather than being a somewhat lone ranger

**Comment by SCDeveloper** [comment]
Argon2d is actively developed. If development ceased, we could then fall back to ctAES. Thoughts?

**Comment by empinel** [comment]
I honestly have no issues but you need to see the following points:

1) No one has used crypter hashing to be with Argon2d so if there is a screwup, we are on our own

2) While actively developed, seeing the amount of changes that is being done to the Argon2d code, is it a really good idea to have a password hashing algorithm modified for high RAM consumption .

3) ctAES, unlike Argon2d is backwards compatible with the current system and vice versa. So if something say we're to get fucked up, any major change will cause the existing passwords to invalidate (not 100% certain)

**Pull request merged**
