### PR TITLE
PoW Hash Algorithm Updated to Argon2d.

### PR DESCRIPTION
**Pull request by CryptoDJ**
#### What's this pull request do?
Changes the PoW hash algorithm to Argon2d.
#### Did you test this pull request?
Not tested yet.
#### Any background context you want to provide?
Current PoW algorithm is Scrypt.  Darksilk will use Argon2d at deployment.  With the added wallet miner, we can start a Argon2d chain.
#### Questions:
- Does the readme or documentaion need an update? No.
- Does this add new C++ dependencies which need to be added? No.
- Does this change the chain or fork the network? Yes, it will fork.  Protocol version is increased. This PR needs a new chain.

### CODE REVIEW

**Comment by GregoryBetz** [comment]
Argon2d mining is working very well. The blocks are 1.25 DRKSLK each without stormnodes up. I'm not sure if this branch has the function that keeps pow at 1 even with no stormnodes. 

Transactions do not work, but I think that was known. I'll try a few different types of transactions from the terminal and see if there is a different result. At block 50 right now, so I'm waiting to see how pos works as well.

**Comment by empinel** [comment]
What are the errors?

**Comment by GregoryBetz** [comment]
https://github.com/SCDeveloper/DarkSilk-Release-Candidate/issues/193

**Comment by empinel** [comment]
Okay, thanks

**Pull request closed without merging**
