### PR TITLE
[Core] PoW to Argon2d

### PR DESCRIPTION
**Pull request by CryptoDJ**
#### What's this pull request do?
Changes the PoW hash algorithm to Argon2d.
#### Did you test this pull request?
Not tested yet.
#### Any background context you want to provide?
Current PoW algorithm is Scrypt.  Darksilk will use Argon2d at deployment.  With the wallet miner, we can start a Argon2d chain.
#### Questions:
- Does the readme or documentaion need an update? No.
- Does this add new C++ dependencies which need to be added? No.
- Does this change the chain or fork the network? Yes, it will fork.  Protocol version is increased. This PR needs a new chain.

### CODE REVIEW

**Comment by GregoryBetz** [comment]
Tested ACK

**Comment by GregoryBetz** [comment]
Mining, PoS, and PoW all work very well. However, there is a bug that causes the menu bar to not load. But, if you delete the database, then restart DarkSilk, and redownload the blockchain, the menu bar works fine. Strange...

**Comment by hexxcointakeover** [comment]
windows/mingw has still problems to compile with new algos.
some work to do...

**Comment by empinel** [comment]
https://github.com/empinel/DarkSilk-Release-Candidate/tree/Argon2dx

**Pull request closed without merging**
