### PR TITLE
[Build] Univalue In Qt Project and Make Files.

### PR DESCRIPTION
**Pull request by empinel**
### What's this pull request do?

Adds univalue build steps to Qt project file and updates univalue code with latest.
### Did you test this pull request?

The Qt project build was tested. Univalue code not tested.
### Any background context you want to provide?

Univalue is a JSON lib and will be used to replace JSON spirit. Univalue is faster and needed for the CLI version.
### Questions:

-    Does the readme or documentaion need an update? Yes, it is included.
-    Does this add new C++ dependencies which need to be added? No.
-    Does this change the chain or fork the network? No.

Updated univalue code.

Code forked from https://github.com/jgarzik/univalue on 2016-03-31.

### CODE REVIEW

**Comment by GregoryBetz** [comment]
utACK. I was just about to finally upgrade rpcserver et al to Univalue and this update is very much needed.

**Comment by empinel** [comment]
It has no conflicts with the base branch

**Comment by CryptoDJ** [comment]
Please test it and I will merge.

**Comment by empinel** [comment]
It compiles and it runs

**Comment by CryptoDJ** [comment]
We can test when we start using UniValue instead of Spirit's Value for RPC JSON return.

**Pull request merged**
