### PR TITLE
[Cleanup] Depreciation of Alerts

### PR DESCRIPTION
**Pull request by empinel**
#### What is the purpose of this pull request (PR)?

Removal of the in-wallet alerting function

#### Any background context to help the reviewer?

Following latest BitCoin Standards

#### Was this PR tested and how (if not, why)?

Tested on Ubuntu 15.04

#### Does this PR resolve an open issue (reference issue #)?
1. Fixes issue #

#### More Questions:
- Does the knowledge base need an update? No
- Does this PR add or change dependencies? No
- Does this change the chain or fork the network? Nah

### CODE REVIEW

**Comment by empinel** [comment]
Why is this not getting tested?

**Comment by empinel** [comment]
This has also been tested on Ubuntu 15.04

**Comment by AmirAbrams** [comment]
I think Spencer wants to keep the public alert system.

**Comment by empinel** [comment]
Seeing that we do not have an alternative, keeping it to some extent seems logical.

**Comment by empinel** [comment]
But BitCoin has bid adieu to the Alert System

**Comment by SCDeveloper** [comment]
We are keeping public alert.

**Pull request closed without merging**
