### PR TITLE
Shift some stuff up to consensus.h and ChainParams, amongst the other changes

### PR DESCRIPTION
**Pull request by empinel**

### CODE REVIEW

**Comment by empinel** [comment]
Note: Please integerate Travis Cl for your Repo, Spencer so that when merging commits, it get's auto-tested first.

Also, I haven't tested these changes

**Comment by empinel** [comment]
Darn it! There are conflicts

**Comment by SCDeveloper** [comment]
There will be more

**Comment by SCDeveloper** [comment]
The master branch isn't launching and this will be due to my last commit obviously, lol, but its down to the darksilkd, darksilk-cli and int main declarations. Should be an easy fix but as I said on my other comment, it is 3am so I am passing out for today, 16 hours of working is enough for one day.

**Comment by empinel** [comment]
Okay. I'll keep on merging

**Comment by empinel** [comment]
Fixed conflicts, also please look at https://github.com/SCDeveloper/DarkSilk-Release-Candidate/issues/104

**Comment by empinel** [comment]
NOTE: REPOSITORY IS CORRUPT, NEW REPO AND PULL REQUEST CREATED!

**Comment by SCDeveloper** [comment]
Reviewing.....

**Pull request closed without merging**
