### PR TITLE
[Core] Update to CreateCoinStake.

### PR DESCRIPTION
**Pull request by CryptoDJ**
#### What's this pull request do?
Correction to CreateCoinStake.
#### Did you test this pull request?
No, in the process.
#### Questions:
- Does the readme or documentaion need an update? No.
- Does this add new C++ dependencies which need to be added? No.
- Does this change the chain or fork the network? No.

removes stormnode payments in CreateCoinStake.

### CODE REVIEW

**Comment by SCDeveloper** [comment]
Nice, I see this is to get the vouts correct for stake, stormnode payments etc. and a work in progress. I will wait to see the next step and will not merge this. Obviously testing is necessary too.

**Comment by empinel** [comment]
Amir, this pull request will create a problem in my pull request where I shift some variables to chainparams

**Comment by SCDeveloper** [comment]
Amirs change takes priority, but do not merge your branch to his changes until his is fully tested and merged.

**Comment by empinel** [comment]
I know, just saying that it will create conflicts - otherwise sorry for wasting your time

**Comment by empinel** [comment]
This pull request can be closed, the Argon2d PR already has the commit that this PR has

**Pull request closed without merging**
