### PR TITLE
[Core] Refactor PoS/PoW Related Functions, Depreciate Alerts, Refactor Rewards, Implement BIP9 and WalletInterface

### PR DESCRIPTION
**Pull request by empinel**
#### What is the purpose of this pull request (PR)?

To put Proof Of Work Related and Proof Of Stake Related Functions and Variables (as mentioned in BitCoin, sort of) in it's own file (proofs.cpp/.h), shifting WalletInterface and it's subsequently required functions to (wallet interface.cpp/.h), the reward related functions and variables and remove the Alerting Feature due to it's depreciation

#### Any background context to help the reviewer?

I doubt

#### Was this PR tested and how (if not, why)?

* Tested on Ubuntu 15.04 LTS on VMWare Fusion running on Mac OS X El Capitan.
* Debug Logs: https://mega.nz/#!xwBDEBhI!jMW5R4Gj_iJ5lX-0GefjkF1POVXTdf128D9XzxZhMyM

#### Does this PR resolve an open issue (reference issue #)?
It absolutely does not

#### Screenshots (if appropriate)

Inappropraiate

#### More Questions:
- Does the knowledge base need an update? No
- Does this PR add or change dependencies? No
- Does this change the chain or fork the network? No

### CODE REVIEW

**Comment by SCDeveloper** [comment]
I can see from the log that the wallet connects and syncs fine, however did you test pos, pow and transaction send/receive?

**Comment by empinel** [comment]
You're on Skype?

**Comment by CryptoDJ** [comment]
I think this should have been split into four PR:

1. Refactor PoS/PoW Related Functions
2. Depreciate Alerts
3. Implement BIP9
4. WalletInterface

This PR has many goals which makes is difficult to test, review and regress if needed.

**Comment by empinel** [comment]
It has been tested

**Comment by SCDeveloper** [comment]
I passed a privkey to empinel to fund the wallet and enable him to test tx's and PoS transactions. He will also need to do a setgenerate true 16 in the wallet to enable PoW mining to test.

**Comment by empinel** [comment]
The mining works, due to node issues - I cannot seem to connect to Amir's Node

**Pull request closed without merging**
