### PR TITLE
Heck lots of changes

### PR DESCRIPTION
**Pull request by empinel**
#### Questions:
- Does the readme or documentaion need an update?
- Does this add new C++ dependencies which need to be added?
- Does this change the chain or fork the network?

### CODE REVIEW

**Comment by CryptoDJ** [comment]
NACK.  "Heck lots of changes" does not describe the purpose of this pull.  We need small, atomic pull request that have precise goals.  Please break this pull into smaller working pulls.

Please see the contribution document for more info:  [CONTRIBUTING.md](https://github.com/SCDeveloper/DarkSilk-Release-Candidate/blob/main/CONTRIBUTING.md)

Since this pull doesn't compile, there is no way it was tested.

**Comment by SCDeveloper** [comment]
I am closing this pull request until it meets the required elements as mentioned in [CONTRIBUTING.md](https://github.com/SCDeveloper/DarkSilk-Release-Candidate/blob/main/CONTRIBUTING.md)

**Comment by empinel** [comment]
Okay, I remember compiling it - I'll go home and do it

**Comment by CryptoDJ** [comment]
115 commits and 777 changed files is way too much for one pull request.  Try to make small, digestible changes that stick to your goals.  For SelectCoins from Emercoin, all the code in the pull commits should be related to that functionality so likely there would be only 1 commit.  You can  squash commits using Git.  see [Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)

**Comment by empinel** [comment]
Okay Amir, thanks

**Comment by empinel** [comment]
Amir, rebasing is causing way too many problems

**Pull request closed without merging**
