### PR TITLE
New Genesis Block Generation Code

### PR DESCRIPTION
**Pull request by empinel**

### CODE REVIEW

**Comment by empinel** [comment]
A Much Efficient Genesis Creation Systen

**Comment by SCDeveloper** [comment]
Your previous commit doesn't build as testnet is not declared in main.cpp

**Comment by SCDeveloper** [comment]
Have you tested this code by generating a new genesis hash?

**Comment by empinel** [comment]
Yes, it does work using printf, not LogPrintf

**Comment by SCDeveloper** [comment]
Yes you'll need printf to print to console and make life easier.

**Comment by empinel** [comment]
It was supposed to use printf but I chose LogPrintf in case you're running windows

**Comment by SCDeveloper** [comment]
Fair enough ;)

**Pull request merged**
