### PR TITLE
[Miner] wallets hashmeter fix

### PR DESCRIPTION
**Pull request by hexxcointakeover**
#### What's this pull request do?
removes the debug.log spam from hashmeter
#### Did you test this pull request?
yes, with windows.
#### Any background context you want to provide?
old code makes debug.log to gigabytes
#### Questions:
- Does the readme or documentaion need an update?
no
- Does this add new C++ dependencies which need to be added?
no
- Does this change the chain or fork the network?
no

### CODE REVIEW

**Comment by CryptoDJ** [comment]
I will test on Linux.

**Comment by hexxcointakeover** [comment]
feel free to remove some tabs to look code better in the editor

**Comment by CryptoDJ** [comment]
I couldn't merge because the branch is out of date with the base:
> This branch is out-of-date with the base branch
Merge the latest changes from main into this branch. 

I replaced this PR with #226 and it has your hash meter fix commit.

**Comment by CryptoDJ** [comment]
I merged the replacement PR #226

**Pull request closed without merging**
