### PR TITLE
A Lot of Changes [COMPILABLE]

### PR DESCRIPTION
**Pull request by empinel**
Basically #102 but without the darn lot of commits (due to my stupidity)

### CODE REVIEW

**Comment by SCDeveloper** [comment]
CHANGELOG hasn't been kept up to date as of late. Probably best to scrub and redo once all code is final. Another option is to just do away with the CHANGELOG completely or to simply simplify the CHANGELOG down to a paragraph of information and a github links.

**Comment by SCDeveloper** [comment]
Merged so I can fix the build issues with testnet not being declared. Doesn't compile like you said :D

**Comment by empinel** [comment]
Well, my mistake - I think we should install Travis Ci for your repository

**Comment by SCDeveloper** [comment]
We will be switching repo though and that will cause nightmares in the long run. As we are a small team, myself and Amir who are working on the wallet and now yourself I do not believe it actually worth the time until the codebase is complete and within the correct repo. However add me on skype: spencer.lievens and myself, yourself and amir can test and converse.

**Comment by empinel** [comment]
I will contact you on skype

**Pull request merged**
