### PR TITLE
[Build] Univalue In Qt Project and Make Files.

### PR DESCRIPTION
**Pull request by CryptoDJ**
#### What's this pull request do?
Adds univalue build steps to Qt project file and updates univalue code with latest.
#### Did you test this pull request?
The Qt project build was tested.  Univalue code not tested.
#### Any background context you want to provide?
Univalue is a JSON lib and will be used to replace JSON spirit.  Univalue is faster and needed for the CLI version.
#### Questions:
- Does the readme or documentaion need an update? Yes, it is included.
- Does this add new C++ dependencies which need to be added? No.
- Does this change the chain or fork the network? No.

Updated univalue code.

Code forked from https://github.com/jgarzik/univalue on 2016-03-31.

### CODE REVIEW

**Comment by GregoryBetz** [comment]
Why hasn't this been merged yet?

**Comment by CryptoDJ** [comment]
I'll resolve the conflicts and test.  Not sure why we didn't merge.

**Comment by empinel** [comment]
https://github.com/SCDeveloper/DarkSilk-Release-Candidate/pull/228

**Comment by empinel** [comment]
https://github.com/SCDeveloper/DarkSilk-Release-Candidate/pull/228

**Comment by CryptoDJ** [comment]
This PR is replaced by #228 . Closing.

**Pull request closed without merging**
