### PR TITLE
[Refactor] Adds file consensus.h

### PR DESCRIPTION
**Pull request by GregoryBetz**
#### What is the purpose of this pull request (PR)?
Creates a new file in the consensus directory called consensus.h.
#### Any background context to help the reviewer?
Refactors the file system to stay aligned with BTC and Dash 0.12 updates.
#### Was this PR tested and how (if not, why)?
Mining, PoS, and transactions successful. Builds with no new errors or warnings.

#### More Questions:
- Does the knowledge base need an update? No.
- Does this PR add or change dependencies? No.
- Does this change the chain or fork the network? No.

### CODE REVIEW

**Comment by CryptoDJ** [comment]
Nice work.  utACK.

**Comment by SCDeveloper** [comment]
Merging as this is nice and atomic, perfect example of how commits should be 👍

**Comment by SCDeveloper** [comment]
Not to mention because it works :D

**Comment by GregoryBetz** [comment]
Thanks guys!

**Comment by CryptoDJ** [comment]
It also helps with the chainActive work.

**Pull request merged**
